In [ ]:
import torch
from torch import nn

batch_size = 8
out = torch.ones((batch_size,4)) * 8
softmax = nn.Softmax(dim=-1)
out = softmax(out)
print(out)
# real = torch.zeros_like(out)
# for i in range(batch_size):
#     real[i][i%4] = 1
# crit = nn.CrossEntropyLoss()
# crit(out, real)
# real = torch.tensor([[0, 0, 0, 1]])
# nn.CrossEntropyLoss()

In [ ]:
x, y = 1, 2
x, y

In [ ]:
import torch
from model.my_model import BertLSTM1
from data.dataset import NewsDataset

test_dataset = NewsDataset()
model = BertLSTM1()
y = model(test_dataset[0][0].unsqueeze(0), test_dataset[0][1].unsqueeze(0), test_dataset[0][2].unsqueeze(0))
res = torch.max(y, dim=2)

In [ ]:
import torch

x = torch.randn(2, 4, 5)
y = torch.sum(x, dim=1)
x, y

In [ ]:
with torch.no_grad():
    print(1)

In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")


In [ ]:
with open('preprocess/preprocessed_data/small_test_keywords.txt', 'r') as f:
        lines = f.readlines()
        for line in lines:
            embedding = tokenizer.encode_plus(line.strip(), padding='max_length', max_length=50, return_tensors='pt')
            print(embedding)

In [10]:
from torch.utils.data import DataLoader
from train_mtgpu import Trainer

In [16]:
def _get_sep_pos(target_ids):
        sep_pos = torch.zeros((target_ids.shape[0]))
        for i in range(target_ids.shape[0]):
            for j in range(target_ids.shape[1]):
                if target_ids[i][j] == 102:
                    sep_pos[i] = j
                    break
        return sep_pos

In [19]:
dataset = NewsDataset()
data_loader = DataLoader(batch_size=32, dataset=dataset)
# a, b, c = data_loader[3]
for a, b, c in data_loader:
    pos = _get_sep_pos(c)
    print(c[0])
    break
pos, pos.shape


tensor([ 101, 5739, 1744, 4767, 3779, 1062, 1385, 1355, 4385, 2342, 1798, 3779,
        4506, 5500,  817, 7604, 1285,  124,  945, 8013,  102,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0])


(tensor([20., 10., 17., 20., 17., 27., 14., 23., 22., 31., 13., 17., 22., 15.,
         21., 13., 20., 19., 21., 17., 20., 13., 23., 19., 18., 23., 25., 20.,
         12., 28., 16., 13.]),
 torch.Size([32]))

In [23]:
from torch import nn
import math
criterion = nn.CrossEntropyLoss()
a = torch.tensor([0.2, 0.8])
softmax = nn.Softmax()
softmax(a)


/tmp/ipykernel_327806/675685718.py:6: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax(a)


tensor([0.3543, 0.6457])

In [26]:
b = torch.tensor([1.0, 0.0])
loss = criterion(a, b)
loss2 = - (((1 * math.log(0.3543)) + (0)) + ((0) + (1*math.log(0.3543))))
loss, loss2 / 2

(tensor(1.0375), 1.0376112671107107)